x-environment: &common-env
  FEMBOYFANS_HOSTNAME: http://localhost:${EXPOSED_SERVER_PORT:-3001}
  FEMBOYFANS_REDIS_URL: redis://redis
  FEMBOYFANS_OPENSEARCH_HOST: opensearch
  FEMBOYFANS_MEMCACHED_SERVERS: memcached
  FEMBOYFANS_IQDB_SERVER: http://iqdb:5588
  FEMBOYFANS_RECOMMENDER_SERVER: http://recommender:5000
  # Must be externally accessible
  FEMBOYFANS_REPORTS_SERVER: http://localhost:${EXPOSED_SERVER_PORT:-3001}/reports
  # Must be internally accessible
  FEMBOYFANS_REPORTS_SERVER_INTERNAL: http://reports:3000
  FEMBOYFANS_REPORTS_ENABLED: 1
  FEMBOYFANS_DISCORD_SITE: http://localhost:3003
  FEMBOYFANS_DISCORD_SECRET: super_secret_for_url_discord
  FEMBOYFANS_REPORT_KEY: super_secret_key_for_reports_signature
  # These are just development secrets, do not use them in production
  FEMBOYFANS_PROTECTED_FILE_SECRET: 6686a6413d90c43d5e82403ef271ec25d13cc24e3bfcdd094e73d1eff22a3567
  FEMBOYFANS_REPLACEMENT_FILE_SECRET: b35bc54cdc0d0436fc5867c7ef88f9b10a37ae20a06b37e67614fe60019d7bb1
  SECRET_TOKEN: 1c58518a891eff4520cadc59afa9e378a9325f1247544ff258096e497f095f45
  SESSION_SECRET_KEY: 44b4f44e9f253c406cbe727d403d500c1cecff943e4d2aea8f5447f28846fffe
  # Hide annoying output from libvips on corrupt files
  VIPS_WARNING: "0"

x-depends-on: &common-depends-on
  opensearch:
    condition: service_healthy
  memcached:
    condition: service_started
  postgres:
    condition: service_started
  redis:
    condition: service_started

services:
  femboyfans:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    user: ${DOCKER_USER:-root}
    image: femboyfans
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - post_data:/app/public/data
      - ./docker/cron_tasks/daily:/etc/periodic/daily
    environment:
      <<: *common-env
      RAILS_ENV: development
    depends_on:
      <<: *common-depends-on
      autocompleted:
        condition: service_started
      iqdb:
        condition: service_started
      recommender:
        condition: service_started
      reports:
        condition: service_started
    tty: true

  # For this service to work properly, it must be accessible from /tags/autocomplete.json on the same url as the primary app
  autocompleted:
    image: ghcr.io/e621ng/autocompleted:8807bc8658f594cd0de04de1c272c3a2f917fc48
    command: /app/autocompleted
    environment:
      SERVER_ADDR: autocompleted:8118
      PG__USER: femboyfans
      PG__HOST: postgres
      PG__PORT: 5432
      PG__DBNAME: femboyfans_development
      PG__POOL__MAX_SIZE: 1

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./public:/app/public
      - post_data:/app/public/data
      - ./docker/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      <<: *common-env
      NGINX_PORT: ${EXPOSED_SERVER_PORT:-3001}
    depends_on:
      - autocompleted
      - femboyfans
      - reports
    ports:
      - "${EXPOSED_SERVER_PORT:-3001}:${EXPOSED_SERVER_PORT:-3001}"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=femboyfans
      - POSTGRES_DB=femboyfans_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${EXPOSED_POSTGRES_PORT:-34518}:5432"

  redis:
    image: redis:7.0.10-alpine
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "${EXPOSED_REDIS_PORT:-34519}:6379"

  memcached:
    image: memcached:1.5.22-alpine

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - logger.level=WARN
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    init: true
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 12
      test: curl "opensearch:9200/_cluster/health?wait_for_status=yellow&timeout=2s"

  iqdb:
    image: ghcr.io/e621ng/iqdb:ad5e363879d4e4b80a0821253ae610b7859c5d32
    command: iqdb http 0.0.0.0 5588 /iqdb/iqdb.db
    volumes:
      - iqdb_data:/iqdb

  recommender:
    image: ghcr.io/femboyfans/recommender:b29409d748333c99beb1faf2dc7b902cefdf26cf
    volumes:
      - recommender_data:/recommender/data
    environment:
      - DATABASE_URL=postgres://femboyfans:@postgres/femboyfans_development
      - OPENBLAS_NUM_THREADS=1
      - TRAINING_THREADS=4

  # By default, this is bound to /reports on the same url as the primary app for external access
  # To change this, set the FEMBOYFANS_REPORTS_SERVER env variable
  # For internal access, change the FEMBOYFANS_REPORTS_SERVER_INTERNAL env varable (defaults to http://reports:3000)
  reports:
    image: ghcr.io/femboyfans/reports:7773b0aaf70ab47b6d2f30eeae813cda51684603
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=femboyfans
      - REPORTS_REDIS_URL=redis://redis/1
      - REPORTS_REPORT_KEY=${FEMBOYFANS_REPORT_KEY:-super_secret_key_for_reports_signature}
    volumes:
      - type: bind
        source: ./config/master.key
        target: /app/config/master.key
      - type: bind
        source: ./config/credentials.yml.enc
        target: /app/config/credentials.yml.enc
    ports:
      - "${EXPOSED_REPORTS_PORT:-3002}:3000"

  # Discord integration

  discordbot:
    image: ghcr.io/femboyfans/discordbot:db89701ea31ff810059fa222cf44f35484c30149
    environment:
      DISCORD_TOKEN: ${DISCORDBOT_DISCORD_TOKEN-}
      DISCORD_ID: ${DISCORDBOT_DISCORD_ID-}
      DISCORD_SECRET: ${DISCORDBOT_DISCORD_SECRET-}
      REDIS_URL: ${DISCORDBOT_REDIS_URL:-redis://redis/2}
      REDIS_CHANNELS_TICKETS: ${DISCORDBOT_CHANNELS_TICKETS:-ticket_updates}
      GUILD_ID: ${DISCORDBOT_GUILD_ID-}
      ADMIN_ROLE: ${DISCORDBOT_ADMIN_ROLE-}
      JOINER_PORT: ${JOINER_PORT:-3003}
      JOINER_URL: ${DISCORDBOT_JOINER_URL:-http://localhost:${EXPOSED_JOINER_PORT:-3003}}
      JOINER_SECRET: ${FEMBOYFANS_DISCORD_SECRET:-super_secret_for_url_discord}
      JOINER_CHANNEL_ID: ${DISCORDBOT_JOINER_CHANNEL_ID-}
      AUDIT_LOG_CHANNEL_ID: ${DISCORDBOT_AUDIT_LOG_CHANNEL_ID-}
      EVENT_CHANNEL_ID: ${DISCORDBOT_EVENT_CHANNEL_ID-}
      TICKET_CHANNEL_ID: ${DISCORDBOT_TICKET_CHANNEL_ID-}
      MEMBER_ROLE_ID: ${DISCORDBOT_MEMBER_ROLE_ID-}
      BASE_URL: ${DISCORDBOT_BASE_URL:-http://localhost:${EXPOSED_SERVER_PORT:-3001}}
      FETCH_URL: ${DISCORDBOT_FETCH_URL:-http://nginx:${EXPOSED_SERVER_PORT:-3001}}
      CDN_HOST: ${DISCORDBOT_CDN_HOST:-localhost:${EXPOSED_SERVER_PORT:-3001}}
      BLACKLISTED_TAGS: ${DISCORDBOT_BLACKLISTED_TAGS:-}
      STAFF_CATEGORIES: ${DISCORDBOT_STAFF_CATEGORIES:-}
      SAFE_CHANNELS: ${DISCORDBOT_SAFE_CHANNELS:-}
      ENCRYPTION_KEY: ${DISCORDBOT_ENCRYPTION_KEY:-o7SrC4IZKDeX4WOC4Zulp2xhQxNM1tvkHmi4Wh8AEqbjdCR3vFQplQCPE6FlnisLCLbs3Axeg0B96hYr}
      ENCRYPTION_SALT: ${DISCORDBOT_ENCRYPTION_SALT:-apPyQsjNgUOIiAV62Evly0qgJATdocWwKT0vsdow}
    init: true
    ports:
      - "${EXPOSED_JOINER_PORT:-${JOINER_PORT-}}:${JOINER_PORT:-3003}"
    profiles:
      - discord

  # Useful for development

  tests:
    image: femboyfans
    environment:
      <<: *common-env
      RAILS_ENV: test
    volumes:
      - .:/app
      - ./docker/local_config.rb:/app/config/local_config.rb
      - node_modules:/app/node_modules
    depends_on:
      <<: *common-depends-on
    entrypoint: bundle exec rails test
    profiles:
      - tests

  rubocop:
    image: femboyfans
    volumes:
      - .:/app
      - rubocop_cache:/rubocop_cache
    entrypoint: bundle exec rubocop --cache-root /rubocop_cache
    profiles:
      - rubocop

  linter:
    image: e621
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: yarn run lint
    profiles: 
      - linter

volumes:
  post_data:
  iqdb_data:
  opensearch_data:
  db_data:
  redis_data:
  node_modules:
  rubocop_cache:
  recommender_data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: br-femboyfans
